### ISSUE TITLE
adv_windowlist on MacOS

### ISSUE THREAD

**Issue by duraki** [irssi/scripts.irssi.org#553]
```sh
# in irssi
$ /script load autorun/adv_windowlist.pl

adv_windowlist: Cant locate Text/CharWidth.pm in @INC (you may need to install the Text::CharWidth module) (@INC contains: /Users/<user>/.irssi/scripts 
          /usr/local/Cellar/irssi/1.1.1/share/irssi/scripts 

# in shell
$ /usr/bin/perl -MCPAN -e'install Text::CharWidth'
...
CharWidth.xs:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
...
```

From what I can see, this issue is reflected on both side (the ::CharWidth lib, and this script). Is the script supported for GNU/Linux only?

**Comment by brownhead** [comment]
You may be missing the dependencies required to build Perl modules (the relevant brew package is `perl-build`).

**Comment by duraki** [comment]
Hi @brownhead, just tried that:

```
# this installed correctly
$ sudo brew reinstall perl && sudo brew install perl-build && reboot

# but still can't build the CPAN module (above error)
```

**Comment by brownhead** [comment]
I had a very similar problem yesterday that was solved by doing this, unfortunately I'm not even a novice with Perl, and installing a Perl module through cpan for a different script (also on Mac OS X) is the only experience I have with this.

The only other (highly uninformed) thought I have is that maybe running cpan in the way you are isn't doing what brew's maintainers expected. I used the `cpan` tool that was placed in my PATH. First by running `cpan` to get into the interactive shell, then I ran `install module::name`.

I'd recommend at least trying that, but it's a long shot. I'd ping folks in `#irssi` again if it doesn't work, since someone there was able to nudge me in the right direction yesterday.

**Comment by brownhead** [comment]
I also don't think I installed anything as root with sudo, so you might also try instantiating `cpan` with sudo, in case brew tried to add some configuration to your root users bash rc or something.

**Comment by duraki** [comment]
Hey @brownhead, appreciated fast response. That was at least a good start.

System info at base:

```sh
$ perl -v
... v5.18.2

$ irssi -v
irssi 1.1.1 (20180213 1256)
```
```sh
$ cpan
> install Text::CharWidth
(built the module, worked)

$ /usr/bin/perl -MCPAN -e'install Text::CharWidth'
Reading '/Users/dxt/.cpan/Metadata'
  Database was generated on Thu, 15 Nov 2018 19:17:03 GMT
Text::CharWidth is up to date (0.04).

# now irssi crashes on startup
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/<user>/perl5/lib/perl5/darwin-thread-multi-2level/auto/Text/CharWidth/CharWidth.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/<user>/perl5/lib/perl5/darwin-thread-multi-2level/auto/Text/CharWidth/CharWidth.bundle
  Expected in: flat namespace

[1]    66374 abort      irssi
``` 

Also tried `brew reinstall perl --build-from-source` but still getting the same error.

**Comment by brownhead** [comment]
Oh wow, one step forward, two back. We're well out of territory I'd be any help in unfortunately 😞, but good luck.

**Comment by vague666** [comment]
See the last answer and comments here: https://stackoverflow.com/questions/51037258/dyld-lazy-symbol-binding-failed-symbol-not-found-perl-xs-handshake-io-bund

**Comment by duraki** [comment]
@vague666 removing `PERL5LIB` var did indeed help running irssi; still can't make script to work.

**Comment by vague666** [comment]
If that solved one problem, what is the problem now?

**Comment by duraki** [comment]
As per issue:

```sh
# in irssi
$ /script load autorun/adv_windowlist.pl

adv_windowlist: Cant locate Text/CharWidth.pm in @INC (you may need to install the Text::CharWidth module) (@INC contains: /Users/<user>/.irssi/scripts 
          /usr/local/Cellar/irssi/1.1.1/share/irssi/scripts 

# in shell
$ /usr/bin/perl -MCPAN -e'install Text::CharWidth'
...
CharWidth.xs:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
...
```

**Comment by vague666** [comment]
What was the trouble with irssi? I don't see you mention anything about problems running irssi

**Comment by vague666** [comment]
Try reading through this and see if anything helps
https://github.com/Linuxbrew/legacy-linuxbrew/issues/1046

**Comment by vague666** [comment]
I shouldn't have to google for you though, you ought to be able to google the errors as well as I am
